baseURL = "https://himadoya.github.io/himadoya.org"
languageCode = "en-US"
title = "HIMADOYA+"
theme = "OrgNest"
enableRobotsTXT = true
canonifyURLs = true

[[menu.main]]
  name = "Home"
  url = "/"
  weight = 1

[[menu.main]]
  name = "Posts"
  url = "/posts/"
  weight = 2

[[menu.main]]
  name = "About"
  url = "/about/"
  weight = 3

[[menu.main]]
  name = "Team"
  url = "/team/"
  weight = 4

[[menu.main]]
  name = "Our Works"
  url = "/our-works/"
  weight = 5
  
[[menu.main]]
  name = "Archive"
  url = "/archive/"
  weight = 6

[params]
  archiveSections = ["posts", "our-works"]

  [params.orginfo]
    org_name = "HIMADOYA+"
    org_tagline = "Lodaya, Digdaya, Vokasi Juara!"
    contact_phone = ""
    contact_email = ""
    org_address = ""

    [[params.orginfo.socials]]
      name = "instagram"
      url = "https://instagram.com/himadoya"

  [params.homeSections]
    showHero = true
    showWhy = false
    showCTA = false
    showStats = false
    showProcess = false
    showTestimonial = false
    showBottomCTA = false

  [params.hero]
    title = "Lodaya, Digdaya, Vokasi Juara!"
    subtitle = ""
    image = "/images/timelines/2025-1.jpeg"

  [params.why]
    title = ""

    [[params.why.items]]
      icon = ""
      title = ""
      text = ""

  [params.cta]
    image = ""
    title = ""
    description = ""
    buttonText = ""
    buttonLink = ""
    list = [
      "",
      ""
    ]

  [params.stats]
    title = ""
    description = ""

    [[params.stats.items]]
      number = ""
      label = ""

  [params.process]
    title = ""

    [[params.process.steps]]
      title = ""
      description = ""

  [params.testimonial]
    title = ""
    image = ""
    quote = ""
    name = ""
    role = ""

  [params.bottomcta]
    title = ""
    description = ""
    button_text = ""
    button_url = ""

  [params.about]
    introTitle = "About Us"
    introSubtitle = "Our story, vision, and impact."

  [params.timeline]
    title = "Our Journey"

    [[params.timeline.events]]
      year = "2024"
      title = "Awal Mula HIMADOYA"
      description = "Pada tahun 2024, dari keresahan yang nyata tentang sulitnya akses transportasi antara Kampus Cilibende dan Kampus Baranangsiang IPB, lahirlah sebuah inisiatif yang sederhana namun bermakna besar. Delapan mahasiswa IPB yang berdomisili di daerah Lodaya berkumpul, menyatukan suara dan semangat—itulah hari pertama HIMADOYA+ berdiri. Bukan sekadar komunitas, HIMADOYA+ adalah bentuk nyata kepedulian dan solidaritas terhadap sesama mahasiswa."
      image = ""

    [[params.timeline.events]]
      year = "2025"
      title = " Bertumbuh Bersama"
      description = "Memasuki 2025, tepatnya di semester kedua, HIMADOYA+ tak lagi hanya berisi delapan orang. Seiring berjalannya waktu dan semakin kuatnya visi bersama, jumlah anggota bertambah menjadi 15 orang. HIMADOYA+ berkembang menjadi ruang kolaboratif yang mewadahi berbagai aspirasi, ide, dan aksi nyata dari para anggotanya."
      image = "/images/timelines/2025-1.jpeg"

[taxonomies]
  tag = "tags"
  category = "category"

[outputs]
  home = ["HTML", "JSON"]
